const ERROR_CODE = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  INCORRECT_FIELD: 'INCORRECT_FIELD',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  INVALID_EVENT: 'INVALID_EVENT'
}

export { ERROR_CODE };
